<?php

/**
 * @file
 * Define hooks for the enclosure theme. 
 */

# This is necessary to call the views preprocess function.
# Thanks to lukedekker on the #drupal IRC channel
\Drupal::moduleHandler()->loadInclude('inc', 'views', 'views.theme');


/**
 * Prepares variables for views RSS item templates.
 *
 * Default template: views-view-row-enclosure-rss.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - row: The raw results rows.
 */
function template_preprocess_views_view_row_enclosure_rss(&$variables) {

  template_preprocess_views_view_row_rss($variables);
  $item = $variables['row'];
  $variables['enclosure'] = $item->enclosure;

} // end template_preprocess_views_view_row_enclosure_rss

/* 
function kwlug_enclosure_rss_preprocess_views_view_rss(&$variables) {
  template_preprocess_views_view_rss($variables);
  dsm("Whee! in kwlug_enclosure_rss_preprocess_views_view_rss");
  $variables['channel_elements'] = "
     <image>
     <url>http://kwlug.org/sites/kwlug.org/files/kwlug4-podcast.png</url>
     <title>KWLUG Audio Podcast -- MP3 feed</title>
     <link>http://kwlug.org/</link>
     <description>Serving Waterloo region and beyond</description>
     <width>144</width>
     <height>132</height>
     </image>
     <copyright>http://creativecommons.org/licenses/by-sa/4.0/</copyright>
     ";

} // end template_preprocess_views_view_kwlug_rss
*/
 
